version: "3.8"

volumes:
  data:

services:
  strapi:
    image: strapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1337:1337"
    networks:
      - strapi-network

  postgres:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - strapi-network

networks:
  strapi-network:
    name: strapi-network
    driver: bridge
